### ISSUE TITLE
The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by nicollaas94** [felixfbecker/php-language-server#248]
Hi, here is the error ...

```
extensionHost.ts:293[Extension Host] UnexpectedValueException: RecursiveDirectoryIterator::__construct(c:/xampp/htdocs/Vogo\site\public\site\vuejs\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\strip-ansi\node_modules\ansi-regex,c:/xampp/htdocs/Vogo\site\public\site\vuejs\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\strip-ansi\node_modules\ansi-regex): O sistema n�o pode encontrar o caminho especificado. (code: 3) in C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('c:/xampp/htdocs...', 4128)
#1 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('c:/xampp/htdocs...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(130): FilterIterator->next()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->next()
#5 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\felixfbecker\language-server\src\LanguageServer.php(234): IteratorIterator->next()
#6 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#7 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\coroutine.php(70): Generator->send(NULL)
#8 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(NULL)
#9 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#10 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#11 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#12 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#13 C:\Users\Nicollas\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\felixfbecker\language-server\bin\php-language-server.php(51): Sabre\Event\Loop\run()
#14 {main}A.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] PHP process connected
```

The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by felixfbecker** [comment]
See #113
