### ISSUE TITLE
Exception in CompletionProvider

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#291]
```
[Error - 5:29:06 PM] Request textDocument/completion failed.
  Message: TypeError: Argument 1 passed to LanguageServer\CompletionProvider::expandParentFqns() must be of the type array, null given, called in /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/CompletionProvider.php on line 305 and defined in /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/CompletionProvider.php:299
Stack trace:
#0 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/CompletionProvider.php(305): LanguageServer\CompletionProvider->expandParentFqns(NULL)
#1 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/CompletionProvider.php(151): LanguageServer\CompletionProvider->expandParentFqns(Array)
#2 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(362): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#3 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#4 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#5 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#6 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#7 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#8 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#9 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#10 /Users/felix/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#11 {main}
  Code: -32603 
```

**Comment by swedik** [comment]
Hello, will you please fix this bug? I'm still getting same message.
Thanks.

[Error - 11:32:05] Request textDocument/completion failed.
  Message: TypeError: Argument 1 passed to LanguageServer\CompletionProvider::expandParentFqns() must be of the type array, null given, called in /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/CompletionProvider.php on line 305 and defined in /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/CompletionProvider.php:299
Stack trace:
#0 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/CompletionProvider.php(305): LanguageServer\CompletionProvider->expandParentFqns(NULL)
#1 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/CompletionProvider.php(305): LanguageServer\CompletionProvider->expandParentFqns(Array)
#2 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/CompletionProvider.php(151): LanguageServer\CompletionProvider->expandParentFqns(Array)
#3 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(362): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#4 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#5 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#6 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#7 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#8 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#9 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#10 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#11 /home/swed/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#12 {main}
  Code: -32603
