### ISSUE TITLE
Install Error in vscode

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#295]
_From @jimmyphong on February 10, 2017 22:24_

In output console 

MAC Os sierra.

```
[Error - 5:15:37 AM] Server initialization failed.
  Message: Error: Call to undefined function phpDocumentor\Reflection\Types\token_get_all() in /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/phpdocumentor/type-resolver/src/Types/ContextFactory.php:72
Stack trace:
#0 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/phpdocumentor/type-resolver/src/Types/ContextFactory.php(51): phpDocumentor\Reflection\Types\ContextFactory->createForNamespace('LanguageServer', '<?php\ndeclare(s...')
#1 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(97): phpDocumentor\Reflection\Types\ContextFactory->createFromReflector(Object(ReflectionClass))
#2 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/LanguageServer.php(135): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#3 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#4 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/coroutine.php(64): Generator->valid()
#5 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#6 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/LanguageServer.php(158): Sabre\Event\coroutine(Object(Closure))
#7 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#8 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/EmitterTrait.php(88): call_user_func_array(Object(Closure), Array)
#9 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#10 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#11 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#12 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#13 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#14 /Users/emem/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#15 {main}
  Code: -32603
```

_Copied from original issue: felixfbecker/vscode-php-intellisense#73_

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#294

**Comment by felixfbecker** [comment]
This is weird. http://de2.php.net/manual/en/function.token-get-all.php

**Comment by jens1o** [comment]
I think his php binary is broken. He should try reinstalling php.
