### ISSUE TITLE
Error when format document

### ISSUE THREAD

**Issue by netroby** [felixfbecker/php-language-server#296]
```
 Message: Exception: Unable to format file in /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/PhpDocument.php(244): LanguageServer\Formatter::format('<?php\n/**\n * \xE6\x95...', 'file:///home/hu...')
#1 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(179): LanguageServer\PhpDocument->getFormattedText()
#2 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /home/huzhifeng/.vscode/extensions/felixfbecker.php-intellisense-1.1.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
```

**Comment by felixfbecker** [comment]
Can you provide the file you tried to format?

**Comment by netroby** [comment]
sure. but it not opensource code. you can write mail to my mail.
hufeng1987@gmail.com
and i will mail one to you . and you need keep it in secret. or should
delete it after use

Appreciate your time.
----------------------------
Netroby

2017-02-13 16:46 GMT+08:00 Felix Becker <notifications@github.com>:

**Comment by thisboyiscrazy** [comment]
I am having the same problem here is the code in the file:
```<?php

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

require_once('modules/Campaigns/Campaign.php');

class CampaignIDFix
{
    
    function after_save($bean, $event, $arguments)
    {
        
        global $db;
        
        if (! $bean->campaign_id) {
            return ;
        };
        
        $campaign = new Campaign();
        $campaign->retrieve($bean->campaign_id);
        
        if (! $campaign->id) {
            return;
        };
        
        $pq = $db->prepareQuery("SELECT *DELETE FROM campaign_log WHERE target_id = '?'");
        $tresult = $db->executePreparedQuery($pq, array($bean->id));
        
        $campaign_log = new CampaignLog();
        $campaign_log->retrieve_by_string_fields(array(
        "target_type"=>$bean->module_name,
        "target_id"=>$bean->id,
        "related_type"=>$bean->module_name,
        "related_id"=>$bean->id,
        "campaign_id"=>$campaign->id
        ));

        if ($campaign_log->id) {
            return;
        };
        
        $pq = $db->prepareQuery("DELETE FROM campaign_log WHERE (target_type = 'Contacts' target_id = '?'");
        $tresult = $db->executePreparedQuery($pq, array(
            $bean->module_name,
            $bean->id,
            $bean->module_name,
            $bean->id
        ));
        $camplog = new CampaignLog();
        $camplog->campaign_id  = $bean->campaign_id;
        $camplog->related_id   = $bean->id;
        $camplog->related_type = $bean->module_name;
        $camplog->activity_type = "contact";
        $camplog->target_id = $bean->id;
        $camplog->target_type = $bean->module_name;
        $camplog->activity_date = $bean->date_entered;
        $camplog->save();
    }
}
```

**Comment by wkiril** [comment]
I use vscode on windows and have installed the PHP Formatter extension v0.2.4 which uses php-cs-fixer for formatting the code. I've configured it to run on save and this error shows every time I save the file and there is nothing to fix by the formatter. If I have incorrect formatting the formatter fixes it and the error doesn't show up.

**Comment by yamenarahman** [comment]
@kyle-mccarthy Yes! that's happening because of phpcs, is there anyway to ignore it ?

**Comment by asolopovas** [comment]
Same thing over here.
