### ISSUE TITLE
Crash when using += operator

### ISSUE THREAD

**Issue by jens1o** [felixfbecker/php-language-server#316]
Stacktrace:
```
[Error - 8:01:41 PM] Request textDocument/completion failed.
  Message: ErrorException: Undefined property: PhpParser\Node\Expr\AssignOp\Plus::$left in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php:589
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php(589): {closure}(8, 'Undefined prope...', 'C:\\Users\\Jens\\....', 589, Array)
#1 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php(796): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(PhpParser\Node\Expr\AssignOp\Plus))
#2 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\felixfbecker\language-server\src\CompletionProvider.php(274): LanguageServer\DefinitionResolver->getTypeFromNode(Object(PhpParser\Node\Expr\AssignOp\Plus))
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\felixfbecker\language-server\src\Server\TextDocument.php(362): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#4 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#5 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#9 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#10 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#11 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.2\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#12 {main}
  Code: -32603 
```

Code:
```php
    /**
     * Returns this timecode in seconds
     * @return int
     */
    private function toSeconds() {
        $seconds = 0;
        
        $seconds += $this->|
    }
```

**Comment by felixfbecker** [comment]
This may be fixed in latest master

**Comment by jens1o** [comment]
When is the next release scheduled? I'm in need of this operator.

**Comment by felixfbecker** [comment]
released

**Comment by jens1o** [comment]
Thank you, I'll try it out.
