### ISSUE TITLE
Server initialization failed.

### ISSUE THREAD

**Issue by ylsopkok** [felixfbecker/php-language-server#338]
I've upgraded npm to 4.4.1 and it doesn't work.
`[Error - 上午9:12:53] Server initialization failed.
  Message: UnexpectedValueException: RecursiveDirectoryIterator::__construct(d:/react/client\node_modules\.0.1.5@es6-map\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\es5-ext\array\of,d:/react/client\node_modules\.0.1.5@es6-map\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\es5-ext\array\of): Invalid argument in C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('d:/react/client...', 4128)
#1 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('d:/react/client...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(99): FilterIterator->rewind()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->rewind()
#5 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->rewind()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#8 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#9 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(29): Sabre\Event\coroutine(Object(Closure))
#10 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\LanguageServer.php(208): LanguageServer\FilesFinder\FileSystemFilesFinder->find('d:/react/client...')
#11 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#12 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(88): Generator->send(NULL)
#13 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#14 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\LanguageServer.php(290): Sabre\Event\coroutine(Object(Closure))
#15 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), 'd:\\react\\client', 8776)
#16 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\LanguageServer.php(135): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#17 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#18 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#19 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#20 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\LanguageServer.php(158): Sabre\Event\coroutine(Object(Closure))
#21 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#22 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\EmitterTrait.php(88): call_user_func_array(Object(Closure), Array)
#23 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#24 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#25 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#26 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#27 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#28 C:\Users\Jiong\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#29 {main}
  Code: -32603 
`

**Comment by felixfbecker** [comment]
That doesn't look like npm 4. Did you delete node_modules and reinstall?

**Comment by ylsopkok** [comment]
Seems server fail when I open a js project with es6-map or some modules in node_modules.It's ok if this project doesn't have node_modules folder.

**Comment by felixfbecker** [comment]
Closing as it's probably the same as #113
