### ISSUE TITLE
Undefined offset: 4

### ISSUE THREAD

**Issue by jens1o** [felixfbecker/php-language-server#339]
```
[Error - 5:19:48 PM] Error parsing file:///c:/nginx/html/projects/tolerant-php-parser/tests/cases/parser/returnStatement5.php: ErrorException: Undefined offset: 4 in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\nikic\php-parser\lib\PhpParser\ParserAbstract.php:318
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\nikic\php-parser\lib\PhpParser\ParserAbstract.php(318): {closure}(8, 'Undefined offse...', 'C:\\Users\\Jens\\....', 318, Array)
#1 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocument.php(164): PhpParser\ParserAbstract->parse('<?php\n\nreturn', Object(PhpParser\ErrorHandler\Collecting))
#2 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocument.php(119): LanguageServer\PhpDocument->updateContent('<?php\n\nreturn')
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(134): LanguageServer\PhpDocument->__construct('file:///c:/ngin...', '<?php\n\nreturn', Object(LanguageServer\Index\Index), Object(LanguageServer\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#4 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(113): LanguageServer\PhpDocumentLoader->create('file:///c:/ngin...', '<?php\n\nreturn')
#5 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(70): Generator->send('<?php\n\nreturn')
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}('<?php\n\nreturn')
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#9 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#10 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#11 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#12 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#13 {main}
Parsing file:///c:/nginx/html/projects/tolerant-php-parser/tests/cases/parser/returnStatement6.php
[Error - 5:19:48 PM] Error parsing file:///c:/nginx/html/projects/tolerant-php-parser/tests/cases/parser/returnStatement6.php: ErrorException: Undefined offset: 4 in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\nikic\php-parser\lib\PhpParser\ParserAbstract.php:318
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\nikic\php-parser\lib\PhpParser\ParserAbstract.php(318): {closure}(8, 'Undefined offse...', 'C:\\Users\\Jens\\....', 318, Array)
#1 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocument.php(164): PhpParser\ParserAbstract->parse('<?php\n// TODO e...', Object(PhpParser\ErrorHandler\Collecting))
#2 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocument.php(119): LanguageServer\PhpDocument->updateContent('<?php\n// TODO e...')
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(134): LanguageServer\PhpDocument->__construct('file:///c:/ngin...', '<?php\n// TODO e...', Object(LanguageServer\Index\Index), Object(LanguageServer\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#4 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(113): LanguageServer\PhpDocumentLoader->create('file:///c:/ngin...', '<?php\n// TODO e...')
#5 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(70): Generator->send('<?php\n// TODO e...')
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}('<?php\n// TODO e...')
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#9 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#10 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#11 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#12 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#13 {main}
```

The file looks something like this:
```php
<?php

return
```

**Comment by felixfbecker** [comment]
The stack trace does not come from the language server

**Comment by jens1o** [comment]
It does. At least I've installed this extension. Don't worry about the thing, that I browsed through the tolerant php parser by Microsoft.

**Comment by felixfbecker** [comment]
> ErrorException: Undefined offset: 4 in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.1.3\vendor\nikic\php-parser\lib\PhpParser\ParserAbstract.php:318

**Comment by jens1o** [comment]
ah, that's what you mean. So I should create the issue at nikic's repo?

**Comment by felixfbecker** [comment]
Would check if a new release fixed the bug, otherwise open an issue

**Comment by jens1o** [comment]
Okey, first of all I would need to know I can reproduce that without your language server.

**Comment by jens1o** [comment]
No, I couldn't reproduce it with this snippet:
```php
<?php

require_once 'vendor/autoload.php';

use PhpParser\ErrorHandler;
use PhpParser\Parser;

$file = file_get_contents('errorfile.php');

(new class extends Parser\Php7 {
     // took from Parser.php
    public function __construct() {
        $lexer = new PhpParser\Lexer([
            'usedAttributes' => [
                'comments',
                'startLine',
                'endLine',
                'startFilePos',
                'endFilePos'
            ]
        ]);
        parent::__construct($lexer);
    }
})->parse($file, new ErrorHandler\Collecting);
```

**Comment by nikic** [comment]
An issue that looks similar to this was fixed in php-parser 3.0.5. Can you please check your composer.lock to see which version you're using and if it's older check if an update fixes it?

**Comment by jens1o** [comment]
@nikic Yes, for me it does fix the issue.

**Comment by jens1o** [comment]
@felixfbecker can we update the dependencies, so in the next version noone needs to update manually? I may create a pr.

**Comment by felixfbecker** [comment]
Sure!
