### ISSUE TITLE
Unexpected `return`

### ISSUE THREAD

**Issue by jens1o** [felixfbecker/php-language-server#417]
```
ParseError: syntax error, unexpected 'return' (T_RETURN) in C:\nginx\html\projects\php-language-server-fork\php-language-server\src\DefinitionResolver.php:1200
Stack trace:
#0 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\squizlabs\php_codesniffer\autoload.php(101): PHP_CodeSniffer\Autoload::loadFile('C:\\nginx\\html\\p...')
#1 [internal function]: PHP_CodeSniffer\Autoload::load('LanguageServer\\...')
#2 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(190): spl_autoload_call('LanguageServer\\...')
#3 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#4 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#5 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#6 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(286): Sabre\Event\coroutine(Object(Closure))
#7 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), 'c:\\nginx\\html\\p...', 5596)
#8 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(130): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#9 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#10 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#11 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#12 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(153): Sabre\Event\coroutine(Object(Closure))
#13 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#14 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#15 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#16 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#17 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#18 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#19 C:\nginx\html\projects\php-language-server-fork\php-language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#20 {main}: Error: ParseError: syntax error, unexpected 'return' (T_RETURN) in C:\nginx\html\projects\php-language-server-fork\php-language-server\src\DefinitionResolver.php:1200
Stack trace:
#0 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\squizlabs\php_codesniffer\autoload.php(101): PHP_CodeSniffer\Autoload::loadFile('C:\\nginx\\html\\p...')
#1 [internal function]: PHP_CodeSniffer\Autoload::load('LanguageServer\\...')
#2 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(190): spl_autoload_call('LanguageServer\\...')
#3 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#4 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#5 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#6 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(286): Sabre\Event\coroutine(Object(Closure))
#7 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), 'c:\\nginx\\html\\p...', 5596)
#8 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(130): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#9 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#10 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#11 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#12 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\LanguageServer.php(153): Sabre\Event\coroutine(Object(Closure))
#13 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#14 C:\nginx\html\projects\php-language-server-fork\php-language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#15 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#16 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#17 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#18 C:\nginx\html\projects\php-language-server-fork\php-language-server\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#19 C:\nginx\html\projects\php-language-server-fork\php-language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#20 {main}
    at new ResponseError (C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.4.0\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
    at handleResponse (C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:421:48)
    at processMessageQueue (C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:249:17)
    at Immediate.<anonymous> (C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:233:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
e.onUnexpectedError @ shell.ts:439
```
when I change a html file with one php tag and one echoing to the language mode php.

**Comment by jens1o** [comment]
Nevermind, that was just a typo I wrote into that file... I thought I didn't saved a change...
