### ISSUE TITLE
Error on format

### ISSUE THREAD

**Issue by adraax** [felixfbecker/php-language-server#423]
Hi,

In vs code v1.13.1, if you try to format a well formatted PHP class, you get the following error.

I'm using Mac OS X 10.11.1 (15B42) and `PHP 7.1.5 (cli) (built: May 13 2017 13:28:23) ( NTS )`

```
[Error - 11:54:50 AM] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\nclass fb...', 'file:///Users/o...')
#1 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(160): LanguageServer\PhpDocument->getFormattedText()
#2 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
```

**Comment by felixfbecker** [comment]
I need the file you tried to format to reproduce.

**Comment by adraax** [comment]
```
<?php

class fbMessengerCtrl extends jController
{
    const APP_ID = "################";
    const APP_SECRET = "#########################";

    public function pairing()
    {
        $token = "";
        $rep = $this->getResponse("text");
        $rep->content = "unauthorized operation";

        if (!empty($this->param('code'))) {
            $data = $this->apiCall("https://graph.facebook.com/v2.9/oauth/access_token",
            array(
                "client_id" => self::APP_ID,
                "redirect_uri" => "https://portal.eu.ngrok.io/facebook_messenger/pairing",
                "client_secret" => self::APP_SECRET,
                "code" => $this->param('code')
            ));

            if (!empty($data['error'])) {
                $rep->content = json_encode($data['error']);
                return $rep;
            }

            $rep->content = json_encode($data);
        }

        if (!empty($data['access_token'])) {
            $token = $data['access_token'];

            $data = $this->apiCall(
                "https://graph.facebook.com/v2.9/debug_token", array(
                    "input_token" => $token,
                    "access_token" => $token
                ),
                "get"
            );

            if (!empty($data['error'])) {
                $rep->content = json_encode($data['error']);

                return $rep;
            }

            $rep->content = json_encode($data);
        }

        if (!in_array("manage_pages", $data['data']['scopes'])
        || !in_array("pages_messaging", $data['data']['scopes'])) {
            $rep->content = "need rights";
            return $rep;
        } else {
            $data = $this->apiCall("https://graph.facebook.com/v2.9/me/accounts", array(
                'access_token' => $token
            ));

            $rep->content = json_encode($data);
            return $rep;
        }

        return $rep;
    }

    public function test()
    {
        $rep = $this->getResponse();

        $rep->addContent('<h1>Linking</h1>
    <a href="https://www.facebook.com/v2.9/dialog/oauth?client_id=404761106563274&redirect_uri=https://mydomain.com/facebook_messenger/pairing&scope=manage_pages,pages_messaging">Link account</a>');

        return $rep;
    }

    private function apiCall($url, $data, $method = "get")
    {
        $header = [
            "Content-Type:application/json"
        ];

        if ($method == "get") {
            $url .= '?' . http_build_query($data);
        }

        $curl = curl_init($url);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
        curl_setopt($curl, CURLOPT_HEADER, false);
        curl_setopt($curl, CURLOPT_TIMEOUT, 30);

        if ($method == "post") {
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
        }

        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

        $response = curl_exec($curl);
        curl_close($curl);

        return json_decode($response, true);
    }
}

```

**Comment by adraax** [comment]
Same bug with another file, if this can help you.

```
[Error - 6:01:52 PM] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\nrequire_...', 'file:///Users/o...')
#1 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(160): LanguageServer\PhpDocument->getFormattedText()
#2 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /Users/olivier/.vscode/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603
```

```php
<?php

require_once(JELIX_LIB_PATH . '../fb-messenger/fbmessenger.php');

class FbMessenger
{
    /**
     * Request Type get
     */
    const REQUEST_GET = 'get';

    /**
     * Request Type post
     */
    const REQUEST_POST = 'post';

    /**
     * Request Type delete
     */
    const REQUEST_DELETE = 'delete';

    /**
     * Facebook Graph API Url used to send messages
     *
     * @var string
     */
    protected static $apiUrl = 'https://graph.facebook.com/v2.9/';

    /**
     * Page Access Token used to send messages
     *
     * @var string
     */
    protected static $access_token = '';

    /**
     * Init token
     *
     * @param string $token
     * @return void
     */
    public static function init($token)
    {
        self::$access_token = $token;
    }

    public function apiCall($url, $data, $type = self::REQUEST_POST)
    {
        $data['access_token'] = $access_token;

        $header = [
            "Content-Type:application/json"
        ];

        if ($type == self::REQUEST_GET) {
            $url .= '?' . http_build_query($data);
        }

        $curl = curl_init($this->apiUrl . $url);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
        curl_setopt($curl, CURLOPT_HEADER, false);
        curl_setopt($curl, CURLOPT_TIMEOUT, 30);

        if ($type == self::REQUEST_POST || $type == self::REQUEST_DELETE) {
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
        }

        if ($type == self::REQUEST_DELETE) {
            curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "DELETE");
        }

        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

        $response = curl_exec($curl);
        curl_close($curl);

        return json_decode($response, true);
    }
}
```
