### ISSUE TITLE
Saving PHP file crashes language server

### ISSUE THREAD

**Issue by nanaasumadu** [felixfbecker/php-language-server#431]
```
[Error - 8:35:25 AM] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n/**\n*\n*/\n...', 'file:///Users/n...')
#1 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(160): LanguageServer\PhpDocument->getFormattedText()
#2 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /Users/nana/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.4.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
```

**Comment by felixfbecker** [comment]
It actually errors while _formatting_ the file - make sure to disable `formatOnSave`. It's also not crash, just an error. Pretty sure this is tracked already in a different issue and will be solved once we do formatting through the new parser
