### ISSUE TITLE
Formatting crashed

### ISSUE THREAD

**Issue by mberneis** [felixfbecker/php-language-server#445]
Other files in my project format correctly, just this one crashes

```[Error - 12:17:07 PM] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\ndefined('...', 'file:///Users/m...')
#1 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/Server/TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#2 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /Users/mberneis/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
```

**Comment by jackwakefield** [comment]
I'm having the same issue with 1.5.

```[Error - 20:29:59] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\n/*\nPlugi...', 'file:///home/ja...')
#1 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/Server/TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#2 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /home/jackwakefield/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603
```
