### ISSUE TITLE
Trying to get property of non-object in CompletionProvider.php:286

### ISSUE THREAD

**Issue by jens1o** [felixfbecker/php-language-server#455]
```
[Error - 11:26:37 PM] Request textDocument/completion failed.
  Message: ErrorException: Trying to get property of non-object in C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\CompletionProvider.php:286
Stack trace:
#0 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\CompletionProvider.php(286): {closure}(8, 'Trying to get p...', 'C:\\Users\\Jens\\....', 286, Array)
#1 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\Server\TextDocument.php(358): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#2 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#3 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#4 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#5 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#6 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#7 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#8 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#9 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#10 {main}
  Code: -32603 
```
When the language server wants to serve completion, while having a namespace that includes(!) `namespace` like `jens1o\test\namespace`

**Comment by Edison6351** [comment]
i have the same problem i just format a laravel 5.4 controller but error like this:
![image](https://user-images.githubusercontent.com/8285762/29397731-e9d5e6ea-8352-11e7-8fbf-69ef1659593a.png)
