### ISSUE TITLE
count()-Parameter error in the PhpTokenizer.php

### ISSUE THREAD

**Issue by florianrusch** [felixfbecker/php-language-server#461]
Hi,

I'm using your VSCode(1.15.1) extension PHP IntelliSense(1.5.0) with php7.2 on macOS(10.12.6).

I've got this error message every time I saved a Symfony Controller (see below).
```
Error - 9:32:13 AM] Request textDocument/hover failed.
  Message: ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/microsoft/tolerant-php-parser/src/PhpTokenizer.php:78
Stack trace:
#0 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/microsoft/tolerant-php-parser/src/PhpTokenizer.php(78): {closure}(2, 'count(): Parame...', '/Users/florianr...', 78, Array)
#1 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/microsoft/tolerant-php-parser/src/Node.php(433): Microsoft\PhpParser\PhpTokenizer::getTokensArrayFromContent('<?php \n\n/**\n * ...', 0, 513, false)
#2 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/DefinitionResolver.php(139): Microsoft\PhpParser\Node->getDocCommentText()
#3 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/DefinitionResolver.php(115): LanguageServer\DefinitionResolver->getDocBlock(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#4 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/DefinitionResolver.php(234): LanguageServer\DefinitionResolver->getDocumentationFromNode(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#5 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(105): LanguageServer\DefinitionResolver->createDefinitionFromNode(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration), 'FrontendBundle\\...')
#6 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(67): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#7 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(52): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\SourceFileNode))
#8 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\n/**\n * Co...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///Users/f...')
#9 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\n/**\n * Co...')
#10 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///Users/f...', '<?php\n/**\n * Co...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#11 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///Users/f...', '<?php\n/**\n * Co...')
#12 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#13 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\n/**\n * Co...')
#14 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\n/**\n * Co...')
#15 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#16 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#17 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#18 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#19 /Users/florianrusch/.vscode/extensions/felixfbecker.php-intellisense-1.5.0/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#20 {main}
  Code: -32603 
```

Here is the Symfony Controller:
```php
<?php
/**
 * Copyright (c) 2017. Florian Rusch Webservices <fr@florianrusch.de>
 *
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

namespace FrontendBundle\Controller;

use AppBundle\Entity\Board;
use Doctrine\Common\Collections\Criteria;
use FrontendBundle\Library\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class IndexController
 * @package FrontendBundle\Controller
 * @Route("/")
 */
class IndexController extends Controller
{
    /**
     * @Route("/", name="frontend_index_index")
     * @Method("GET")
     */
    public function indexAction(Request $request)
    {
        $boardRepository = $this->getDoctrine()->getManager()->getRepository("AppBundle:Board");
        $boards = $boardRepository->createQueryBuilder('b')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
            ->addCriteria(new Criteria(Criteria::expr()->eq('published', 1)))
            ->setMaxResults(24)
            ->getQuery()
            ->getResult();

        return $this->render('FrontendBundle::index.html.twig', array('boards' => $boards, $request));
    }
}
```

**Comment by felixfbecker** [comment]
This is fixed in the next release. Note that PHP7.2 is still Beta.
