### ISSUE TITLE
RecursiveDirectoryIterator looking for non-existant 'images' folder in workspace root

### ISSUE THREAD

**Issue by pweiss-mri** [felixfbecker/php-language-server#490]
The PHP language server is getting this error (below) shortly after I open vscode every time.  I've edited to sanitize my local paths.  It doesn't cause the language server process to crash so it doesn't offer a prompt to restart it but it also seems to prevent the language server from analyzing any of my code so I don't get any intellisense in this workspace.

This is only an issue in one of my workspaces (where the language server worked before) so it is likely a configuration issue on my part but I'm not sure where to start looking.  It would also be nice if the language server could survive this sort of error and give information about the rest of the workspace in the future.

`UnexpectedValueException: RecursiveDirectoryIterator::construct([workspace root]\images,[workspace root]\images): The system cannot find the path specified. (code: 3) in [user profile]\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43`

**Comment by felixfbecker** [comment]
Is that the full stack trace?
What does your workspace look like?
Did that `images` directory exist at some point?
What client are you using?

**Comment by pweiss-mri** [comment]
That's the only error/stack trace I saw but I'm not sure if there's a log location that I can check.  I'm using this in vscode.  That images directory did exist at some point but hasn't for a while.  I tried removing the `Cache` and `CachedData` folders at `[user profile]AppData\Roaming\Code` and restarting because I figured it might have cached that the folder existed but that didn't seem to help.

My workspace is pretty simple.  I have a few loose files in the root to describe the workspace to other tools/source control and then I have some folders that hold all my PHP code.

**Comment by felixfbecker** [comment]
Sorry but I don't have enough information to help you. Can you provide a reproducable example? I don't see a reason why the server would access `images` if it doesn't exist. It doesn't cache that kind of information. Do you see output in the developer console (Help > Toggle Developer Tools)? Are you using multi-folder workspaces?

**Comment by pweiss-mri** [comment]
I'm not using a multi-folder workspace.  I'm not sure 100% when this started so unfortunately I don't know what caused it to try and reproduce it.  I should have checked the dev tools early on because there are definitely some stack traces in there.  I apologize for not being able to provide a lot of helpful information, I'm grateful for any help you can offer.  Let me know if these stack traces help at all:

```
UnexpectedValueException: RecursiveDirectoryIterator::__construct([workspace root]\images,[workspace root]\images): The system cannot find the path specified. (code: 3) in [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('[workspace root]...', 4128)
#1 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('[workspace root]...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(99): FilterIterator->rewind()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->rewind()
#5 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->rewind()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#8 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#9 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(33): Sabre\Event\coroutine(Object(Closure))
#10 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(203): LanguageServer\FilesFinder\FileSystemFilesFinder->find[workspace root]...')
#11 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#12 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(88): Generator->send(NULL)
#13 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#14 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(286): Sabre\Event\coroutine(Object(Closure))
#15 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), '[workspace root]...', 14704)
#16 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(130): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#17 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#18 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#19 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#20 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(153): Sabre\Event\coroutine(Object(Closure))
#21 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#22 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#23 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#24 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#25 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#26 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#27 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#28 {main}
e.doShow @ messageService.ts:125

extensionHost.ts:384 [Extension Host] PHP process disconnected

extensionHost.ts:384 [Extension Host] rejected promise not handled within 1 second

t._logExtensionHostMessage @ extensionHost.ts:384
shell.ts:419 [felixfbecker.php-intellisense] UnexpectedValueException: RecursiveDirectoryIterator::__construct([workspace root]\images,[workspace root]\images): The system cannot find the path specified. (code: 3) in [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('[workspace root]...', 4128)
#1 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('[workspace root]...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(99): FilterIterator->rewind()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->rewind()
#5 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->rewind()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#8 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#9 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(33): Sabre\Event\coroutine(Object(Closure))
#10 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(203): LanguageServer\FilesFinder\FileSystemFilesFinder->find('[workspace root]...')
#11 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#12 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(88): Generator->send(NULL)
#13 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#14 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(286): Sabre\Event\coroutine(Object(Closure))
#15 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), '[workspace root]...', 14704)
#16 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(130): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#17 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#18 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#19 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#20 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(153): Sabre\Event\coroutine(Object(Closure))
#21 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#22 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#23 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#24 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#25 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#26 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#27 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#28 {main}: Error: UnexpectedValueException: RecursiveDirectoryIterator::__construct([workspace root]\images,[workspace root]\images): The system cannot find the path specified. (code: 3) in [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('[workspace root]...', 4128)
#1 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('[workspace root]...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(99): FilterIterator->rewind()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->rewind()
#5 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->rewind()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#8 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#9 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(33): Sabre\Event\coroutine(Object(Closure))
#10 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(203): LanguageServer\FilesFinder\FileSystemFilesFinder->find('[workspace root]...')
#11 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#12 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(88): Generator->send(NULL)
#13 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#14 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(286): Sabre\Event\coroutine(Object(Closure))
#15 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), '[workspace root]...', 14704)
#16 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(130): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#17 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#18 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#19 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#20 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\LanguageServer.php(153): Sabre\Event\coroutine(Object(Closure))
#21 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#22 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#23 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#24 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#25 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#26 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#27 [user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#28 {main}
	at new ResponseError ([user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse ([user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\node_modules\vscode-jsonrpc\lib\main.js:421:48)
	at processMessageQueue ([user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\node_modules\vscode-jsonrpc\lib\main.js:249:17)
	at Immediate.<anonymous> ([user profile].vscode\extensions\felixfbecker.php-intellisense-1.5.1\node_modules\vscode-jsonrpc\lib\main.js:233:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by felixfbecker** [comment]
What is `[workspace root]...`?

**Comment by pweiss-mri** [comment]
It's the file path to my workspace.  It's looks like C:\git\some\path\to\a\branch.

**Comment by felixfbecker** [comment]
Did you add the ellipsis?

**Comment by pweiss-mri** [comment]
No, that was in the stack trace. It looks like the console was abbreviating the path because it didn't display the full path.

**Comment by pweiss-mri** [comment]
I think I found the issue and it was definitely my fault.  When I had made the images folder it was a symlink to another real folder.  I guess I removed the real folder but not the symlink.  vscode knew not to show the dead symlink in my workspace explorer but when I double check the windows file explorer I saw the dead symlink.  Removing it fixed this issue.

**Comment by MadHed** [comment]
Sounds like a bug to me. I'll open an issue.
