### ISSUE TITLE
Server crashes on PHP file with invalid syntax

### ISSUE THREAD

**Issue by janb87** [felixfbecker/php-language-server#493]
I'm getting a crash because of a invalid php file. The PHP itself is actually a template which is being processed by a command (using Twig) and therefore is invalid. 

Would it be possible to just ignore files which contain an invalid PHP syntax?

The file which is causing the crash can be found here:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Author.php

```
Microsoft\PhpParser\MissingToken::getResolvedName() in /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/DefinitionResolver.php:931
Stack trace:
#0 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/DefinitionResolver.php(713): LanguageServer\DefinitionResolver->resolveClassNameToType(Object(Microsoft\PhpParser\MissingToken))
#1 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/DefinitionResolver.php(725): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\Node\Expression\ObjectCreationExpression))
#2 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/DefinitionResolver.php(583): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#3 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/DefinitionResolver.php(366): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\Node\Expression\Variable))
#4 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/DefinitionResolver.php(293): LanguageServer\DefinitionResolver->resolveMemberAccessExpressionNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#5 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(119): LanguageServer\DefinitionResolver->resolveReferenceNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#6 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(74): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#7 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(155): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#8 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(74): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#9 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(155): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#10 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(67): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#11 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(52): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\SourceFileNode))
#12 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\n\nnamespac...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///home/pr...')
#13 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\n\nnamespac...')
#14 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///home/pr...', '<?php\n\nnamespac...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#15 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///home/pr...', '<?php\n\nnamespac...')
#16 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#17 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\n\nnamespac...')
#18 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\n\nnamespac...')
#19 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#20 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#21 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#22 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#23 /Users/janb/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#24 {main}
```

**Comment by roblourens** [comment]
I can't repro, but it looks like `resolveClassNameToType` would not handle a `MissingToken` correctly.

**Comment by janb87** [comment]
@roblourens Looks like the issue doesn't exist anymore indeed. I've cloned the repo and used a symlink inside VS Code to use the directory of the repo (as describe in https://github.com/felixfbecker/vscode-php-intellisense#contributing). After doing this it didn't crash anymore. Maybe it relates to a change inside a vendor package recently.

Would be a good idea to create a new version of the vs code extension using a fresh build.
