### ISSUE TITLE
Call to a member function isStatic() on null

### ISSUE THREAD

**Issue by kokororin** [felixfbecker/php-language-server#546]
Hi

There is problem with this extension on my computer.
Here is the PHP version.
```
PHP 7.0.24-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Sep 28 2017 16:33:02) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.20-2~ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

```
[Extension Host] Error: Call to a member function isStatic() on null in /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php:102
Stack trace:
#0 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(121): LanguageServer\TreeAnalyzer->collectDiagnostics(Object(Microsoft\PhpParser\Node\Expression\Variable))
#1 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\Variable))
#2 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#3 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(137): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\ArgumentExpression))
#4 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\DelimitedList\ArgumentExpressionList))
#5 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#6 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\BinaryExpression))
#7 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\BinaryExpression))
#8 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#9 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#10 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(137): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\IfStatementNode))
#11 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#12 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(137): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\FunctionDeclaration))
#13 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(59): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\SourceFileNode))
#14 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\r\r\n/**\r\r\n ...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///home/ko...')
#15 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\r\r\n/**\r\r\n ...')
#16 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///home/ko...', '<?php\r\r\n/**\r\r\n ...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#17 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///home/ko...', '<?php\r\r\n/**\r\r\n ...')
#18 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#19 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\r\r\n/**\r\r\n ...')
#20 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\r\r\n/**\r\r\n ...')
#21 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#22 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#23 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#24 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#25 /home/kotori/.vscode/extensions/felixfbecker.php-intellisense-2.0.3/vendor/felixfbecker/language-server/bin/php-language-server.php(50): Sabre\Event\Loop\run()
#26 {main}
```

**Comment by felixfbecker** [comment]
Already fixed in the latest version.
