### ISSUE TITLE
Parsing foreach() causes exception

### ISSUE THREAD

**Issue by andreymrt** [felixfbecker/php-language-server#561]
Just updated to the new vscode-php-intellisense-2.2.0 version, which references the language server, 
and I keep getting the following error, I've also included the minimal code snippet that can produce the error.

```
[Error - 11:04:17 PM] Request textDocument/hover failed.
  Message: InvalidArgumentException: A compound type can only have other types as elements in C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\phpdocumentor\type-resolver\src\Types\Compound.php:41
Stack trace:
#0 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\DefinitionResolver.php(710): phpDocumentor\Reflection\Types\Compound->__construct(Array)
#1 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\DefinitionResolver.php(403): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#2 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\DefinitionResolver.php(330): LanguageServer\DefinitionResolver->resolveMemberAccessExpressionNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#3 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(176): LanguageServer\DefinitionResolver->resolveReferenceNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#4 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(125): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#5 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#6 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(137): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#7 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\DelimitedList\ExpressionList))
#8 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\EchoExpression))
#9 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(141): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#10 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(137): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ForeachStatement))
#11 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(59): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\SourceFileNode))
#12 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\r\nforeach(...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///c:/User...')
#13 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\r\nforeach(...')
#14 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///c:/User...', '<?php\r\nforeach(...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#15 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///c:/User...', '<?php\r\nforeach(...')
#16 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#17 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\sabre\event\lib\coroutine.php(70): Generator->send('<?php\r\nforeach(...')
#18 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}('<?php\r\nforeach(...')
#19 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#20 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#21 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#22 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#23 C:\Users\andrey\.vscode\extensions\felixfbecker.php-intellisense-2.2.0\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#24 {main}
  Code: -32603 
```

To reproduce, create a php file in an empty directory, paste the following into it, and start VS.Code in that directory

```php
<?php
foreach($Calendar as $day)
	echo $day->Date->format("D");
```

**Comment by felixfbecker** [comment]
This was likely caused by #551. @phil-nelson could you take a look?

In the meantime, you can rollback with the vsix from [2.1.0](https://github.com/felixfbecker/vscode-php-intellisense/releases/tag/v2.1.0) (assuming you use VS Code)

**Comment by phil-nelson** [comment]
Thanks for the detailed report @andreymrt, I have created a PR that I'm fairly certain fixes the issue, if you're able to test with that branch that would be great
