### ISSUE TITLE
array_merge on null in Indexer.php:152

### ISSUE THREAD

**Issue by DObD** [felixfbecker/php-language-server#595]
Mac: 10.13.3 
VS Code: 1.20.0 (I saw this just before the update on VSCode 1.19.x)
PHP Intellisense: 2.2.6
NPM: 5.6.0

In the Console for the Dev tools I see this exception:

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:253 [Extension Host] ErrorException: array_merge(): Argument #2 is not an array in /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/felixfbecker/language-server/src/Indexer.php:152
Stack trace:
#0 [internal function]: {closure}(2, 'array_merge(): ...', '/Users/do/.vsco...', 152, Array)
#1 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/felixfbecker/language-server/src/Indexer.php(152): array_merge(Array, NULL)
#2 [internal function]: LanguageServer\Indexer->LanguageServer\{closure}()
#3 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/sabre/event/lib/coroutine.php(70): Generator->send(NULL)
#4 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}(NULL)
#5 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#6 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#7 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#8 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#9 /Users/do/.vscode/extensions/felixfbecker.php-intellisense-2.2.6/vendor/felixfbecker/language-server/bin/php-language-server.php(50): Sabre\Event\Loop\run()
#10 {main}
```

Let me know if you require more information and where it might be found... Thank you.

**Comment by janekcz69** [comment]
Simple patch:
[patch.txt](https://github.com/felixfbecker/php-language-server/files/2233140/patch.txt)

**Comment by felixfbecker** [comment]
@janekcz69 can you submit a pull request?

**Comment by janekcz69** [comment]
Yes, I try but
Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.
