### ISSUE TITLE
Error: PHP Language Server initialization failed within VSCode (Code -32603)

### ISSUE THREAD

**Issue by ppse** [felixfbecker/php-language-server#654]
Reproduction
1. Simply Starting VS Code on a Xubuntu 16.04 machine with PHP Version 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS ) installed (-> php -v)

2. After Loading VSCode the following Message appears:

Message:
```
[Error - 01:17:07] Server initialization failed.
  Message: ErrorException: unserialize(): Error at offset 180231 of 21867628 bytes in /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/Index/Index.php:206
Stack trace:
#0 [internal function]: {closure}(8, 'unserialize(): ...', '/home/peter/.vs...', 206, Array)
#1 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/Index/Index.php(206): unserialize('a:4:{s:11:"defi...')
#2 [internal function]: LanguageServer\Index\Index->unserialize('a:4:{s:11:"defi...')
#3 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/Index/StubsIndex.php(15): unserialize('C:31:"LanguageS...')
#4 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/LanguageServer.php(187): LanguageServer\Index\StubsIndex::read()
#5 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#6 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/coroutine.php(64): Generator->valid()
#7 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#8 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/LanguageServer.php(289): Sabre\Event\coroutine(Object(Closure))
#9 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), NULL, 604)
#10 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/LanguageServer.php(131): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#11 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#12 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/coroutine.php(64): Generator->valid()
#13 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#14 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/LanguageServer.php(154): Sabre\Event\coroutine(Object(Closure))
#15 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#16 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/src/ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#17 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/Loop/Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#18 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/Loop/Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#19 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#20 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#21 /home/peter/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/bin/php-language-server.php(55): Sabre\Event\Loop\run()
#22 {main}
  Code: -32603
```

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|CPUs|Pentium(R) Dual-Core CPU      
 T4300  @ 2.10GHz (2 x 1921)|
|GPU Status|
2d_canvas: enabled<br>
flash_3d: enabled<br>
flash_stage3d: enabled<br>
flash_stage3d_baseline: enabled<br>
gpu_compositing: enabled<br>
multiple_raster_threads: disabled_off<br>
native_gpu_memory_buffers: disabled_software<br>
rasterization: disabled_software<br>
video_decode: unavailable_software<br>
video_encode: enabled<br>
vpx_decode: unavailable_software<br>
webgl: enabled<br>
webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|3.82GB (0.45GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
vscode-eslint|dba|1.4.12
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
vscode-language-pack-de|MS-|1.25.2

</details>

Intelephense seems to be working though...

What's the meaning of this error message and how could one resolve this error?

**Comment by felixfbecker** [comment]
Does this still happen?

**Comment by felixfbecker** [comment]
Does this still happen?
