### ISSUE TITLE
LanguageServer\Protocol\SymbolInformation trying to operate on was loaded _before_ unserialize()

### ISSUE THREAD

**Issue by Ciantic** [felixfbecker/php-language-server#683]
Testin out just moments ago released VS Code extension and I'm getting following error on the console, as I try to Go to Definition:

```
[Error - 1:27:55 PM] Request textDocument/definition failed.
  Message: ErrorException: LanguageServer\Server\TextDocument::LanguageServer\Server\{closure}(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "LanguageServer\Protocol\SymbolInformation" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\felixfbecker\language-server\src\Server\TextDocument.php:299
Stack trace:
#0 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\felixfbecker\language-server\src\Server\TextDocument.php(299): {closure}(8, 'LanguageServer\\...', 'C:\\Copies\\VSCod...', 299, Array)
#1 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#2 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#3 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#4 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#5 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#6 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#7 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#8 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\felixfbecker\language-server\bin\php-language-server.php(55): Sabre\Event\Loop\run()
#9 {main}
  Code: -32603 
[Error - 1:27:55 PM] Request textDocument/definition failed.
  Message: ErrorException: LanguageServer\Server\TextDocument::LanguageServer\Server\{closure}(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "LanguageServer\Protocol\SymbolInformation" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\felixfbecker\language-server\src\Server\TextDocument.php:299
Stack trace:
#0 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\felixfbecker\language-server\src\Server\TextDocument.php(299): {closure}(8, 'LanguageServer\\...', 'C:\\Copies\\VSCod...', 299, Array)
#1 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#2 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#3 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#4 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#5 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#6 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#7 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#8 C:\Copies\VSCode\data\extensions\felixfbecker.php-intellisense-2.3.8\vendor\felixfbecker\language-server\bin\php-language-server.php(55): Sabre\Event\Loop\run()
#9 {main}
  Code: -32603 
```

**Comment by Ciantic** [comment]
Interesting thing is that it fixed itself as I just waited. I think this happens if you press Go to Definition too quickly, before it's indexed?

**Comment by felixfbecker** [comment]
Looks like the classes in the cache changed. Need to bump the cache version
