### ISSUE TITLE
The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by Enes5519** [felixfbecker/php-language-server#685]
Output:
```
DEBUG     Checking PHPLS_ALLOW_XDEBUG

DEBUG     The xdebug extension is not loaded

[Info  - 7:42:11 PM] Connection to server got closed. Server will restart.
Language server exited with exit code 255
DEBUG     Checking PHPLS_ALLOW_XDEBUG

DEBUG     The xdebug extension is not loaded

[Info  - 7:42:11 PM] Connection to server got closed. Server will restart.
Language server exited with exit code 255
DEBUG     Checking PHPLS_ALLOW_XDEBUG

DEBUG     The xdebug extension is not loaded

[Info  - 7:42:12 PM] Connection to server got closed. Server will restart.
Language server exited with exit code 255
DEBUG     Checking PHPLS_ALLOW_XDEBUG

DEBUG     The xdebug extension is not loaded

[Info  - 7:42:12 PM] Connection to server got closed. Server will restart.
Language server exited with exit code 255
DEBUG     Checking PHPLS_ALLOW_XDEBUG

DEBUG     The xdebug extension is not loaded

[Error - 7:42:13 PM] Connection to server got closed. Server will not be restarted.
Language server exited with exit code 255

```

Console:
```
log.ts:157  INFO no standard startup: panel is active
console.ts:134 [Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG

console.ts:134 [Extension Host] PHP Language Server: DEBUG     The xdebug extension is not loaded

[Extension Host] PHP process connected
[Extension Host] PHP process disconnected
[Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG

[Extension Host] PHP Language Server: DEBUG     The xdebug extension is not loaded

[Extension Host] PHP process connected
[Extension Host] PHP process disconnected
[Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG

[Extension Host] PHP Language Server: DEBUG     The xdebug extension is not loaded

[Extension Host] PHP process connected
[Extension Host] PHP process disconnected
[Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG

[Extension Host] PHP Language Server: DEBUG     The xdebug extension is not loaded

[Extension Host] PHP process connected
[Extension Host] PHP process disconnected
[Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG

[Extension Host] PHP Language Server: DEBUG     The xdebug extension is not loaded

[Extension Host] PHP process connected

The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
t.onDidNotificationChange

[Extension Host] PHP process disconnected
```

**Comment by felixfbecker** [comment]
I have no idea what the cause would be from these logs and cannot reproduce

**Comment by Enes5519** [comment]
I'm just opening the VSCode program and it says they are on the output screen.

**Comment by Enes5519** [comment]
But it's not a problem when I run it myself.
```
C:\php\php.exe C:\Users\xxxx\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php
```

**Comment by arkenidar** [comment]
I discovered (in the hard way) I had not installed Composer.

**Comment by josemi-ca** [comment]
I'm also experiencing this issue.
Was anyone able to fix it? https://stackoverflow.com/questions/56725646/php-language-server-error-on-vscode-connection-to-server-got-closed-server-wil

**Comment by yaayes** [comment]
I've started to see this in the vscode console after the new update if that could help!
and it's really annoying because at the moment you are writing your code the output box open and the cursor lost focus!

> September 2019 (version 1.39)
> Update 1.39.1: The update addresses these issues, including a fix for a security vulnerability.
> 
> Update 1.39.2: The update addresses these issues.

**Comment by PtitPuce** [comment]
Same problem here, I'm trying to investigate the best I can, but have no clue where to start.
One thing for sure : XDebug is working fine. It can be started and used properly.

`CRITICAL  TypeError: Return value of phpDocumentor\Reflection\Types\AbstractList::getValueType() must implement interface phpDocumentor\Reflection\Type, null returned in C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\phpdocumentor\type-resolver\src\Types\AbstractList.php:63
Stack trace:
#0 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\DefinitionResolver.php(1177): phpDocumentor\Reflection\Types\AbstractList->getValueType()
#1 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\DefinitionResolver.php(685): LanguageServer\DefinitionResolver->getTypeFromNode(Object(Microsoft\PhpParser\Node\ForeachValue))
#2 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\DefinitionResolver.php(404): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\Node\Expression\Variable))
#3 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\DefinitionResolver.php(331): LanguageServer\DefinitionResolver->resolveMemberAccessExpressionNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#4 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(175): LanguageServer\DefinitionResolver->resolveReferenceNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#5 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(124): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#6 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#7 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#8 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#9 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#10 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#11 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ForeachStatement))
#12 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#13 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#14 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\ClassMembersNode))
#15 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#16 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(58): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\SourceFileNode))
#17 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\n\nnamespac...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///c:/User...')
#18 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\n\nnamespac...')
#19 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///c:/User...', '<?php\n\nnamespac...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#20 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///c:/User...', '<?php\n\nnamespac...')
#21 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#22 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\sabre\event\lib\coroutine.php(70): Generator->send('<?php\n\nnamespac...')
#23 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}('<?php\n\nnamespac...')
#24 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#25 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#26 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#27 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#28 C:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\bin\php-language-server.php(55): Sabre\Event\Loop\run()
#29 {main}

[Info  - 09:13:41] Connection to server got closed. Server will restart.
DEBUG     Restarted process exited 0

Language server exited with exit code 0
DEBUG     Checking PHPLS_ALLOW_XDEBUG

DEBUG     The xdebug extension is loaded (2.7.0)

DEBUG     Process restarting (PHPLS_ALLOW_XDEBUG=internal|2.7.0|0|*|*)
DEBUG     Running "C:\Program Files (x86)\php\php-7.1.5-Win32-VC14-x64\php.exe" -n -c C:\Users\chalu\AppData\Local\Temp\6CC4.tmp c:\Users\chalu\.vscode\extensions\felixfbecker.php-intellisense-2.3.13\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:58453 --memory-limit=4095M

DEBUG     Checking PHPLS_ALLOW_XDEBUG

DEBUG     Restarted (177 ms). The xdebug extension is not loaded

[Info  - 09:14:06] 7324 files total
[Info  - 09:14:06] Indexing project for definitions and static references`

**Comment by gunnrryy** [comment]
experiencing the same issue on my ubuntu 18.04
also, due to this, the parsing restarts again and again resulting in slowing down the whole system

**Comment by charlesdeb** [comment]
I have something similar but not identical - so it may not even be related. On start-up, my console output in VSCode is telling me:

```
[Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded    console.ts:137

[Extension Host] PHP process connected      console.ts:137
```

This may be normal behaviour.

When I press F5 to start a debugging session, it all appears to work fine, and processing stops at the correct breakpoint. But, I cannot press any buttons in the debug toolbar to continue, step in or step out etc. Keyboard shortcuts don't do anything either. Nothing is logged to the developer tools console or the "problems" area of vscode. The only buttons/commands on the debug toolbar that seem to do anything are ctrl-shift-f5 (restart) and shift-f5 (stop). This used to work fine, but over the last week or two it seems to have stopped. I have tried upgrading to xdebug 2.9 but that didn't make any difference. I think it's a VScode thing. I am using vscode 1.41.0 (although the problem first cropped up in the previous version) and php debug 1.13.0.

**Comment by dktcoding** [comment]
If it helps (since this is still an issue in 2021), in my case, running `composer update` inside the extension folder managed to workaround the issue:

```
cd .vscode/extensions/felixfbecker.php-intellisense-2.3.14/
composer update
```

I assume there might be a dependency failing.
