### ISSUE TITLE
RecursiveDirectoryIterator: The file or directory is not a reparse point

### ISSUE THREAD

**Issue by dwrogers** [felixfbecker/php-language-server#702]
Tried to open a folder and received:

`UnexpectedValueException: RecursiveDirectoryIterator::__construct(x:/[...]/redcap8.11.2_upgrade,x:/[...]/REDCap/redcap8.11.2_upgrade): The file or directory is not a reparse point. (code: 4390) in C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('x:/fast/_PHS/CD...', 4128)
#1 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\webmozart\glob\src\Iterator\GlobIterator.php(75): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('x:/fast/_PHS/CD...', 4128)
#2 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): Webmozart\Glob\Iterator\GlobIterator->__construct('x:/fast/_PHS/CD...')
#3 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#4 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#5 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#6 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(33): Sabre\Event\coroutine(Object(Closure))
#7 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\LanguageServer.php(207): LanguageServer\FilesFinder\FileSystemFilesFinder->find('x:/fast/_PHS/CD...')
#8 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#9 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\coroutine.php(88): Generator->send(NULL)
#10 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#11 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\LanguageServer.php(292): Sabre\Event\coroutine(Object(Closure))
#12 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(160): LanguageServer\LanguageServer->initialize(Object(LanguageServerProtocol\ClientCapabilities), 'x:\\fast\\_PHS\\CD...', 15996, 'file:///x:/fast...')
#13 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\LanguageServer.php(131): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#14 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#15 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#16 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#17 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\LanguageServer.php(154): Sabre\Event\coroutine(Object(Closure))
#18 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Message))
#19 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#20 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#21 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#22 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#23 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#24 C:\Users\drogers\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php(55): Sabre\Event\Loop\run()
#25 {main}
`

**Comment by dwrogers** [comment]
Could it be some sort of capacity issue? A "dir /s" of that directory yields:

     Total Files Listed:
           41459 File(s)  4,568,892,076 bytes
           19073 Dir(s)  790,981,648,384 bytes free
David
