### ISSUE TITLE
error 32603

### ISSUE THREAD

**Issue by citosid** [felixfbecker/php-language-server#773]
I have the already known error 32603 with the file [OpenIDConnectClient.php][1] in the github.com/jumbojett repository (too long to paste it here).

[1]: https://github.com/jumbojett/OpenID-Connect-PHP/blob/master/src/OpenIDConnectClient.php 

These are my global dependencies:

![image](https://user-images.githubusercontent.com/201430/71101284-6a3cf180-2184-11ea-8ea6-8669a03fc747.png)

And these are my local dependencies:

![image](https://user-images.githubusercontent.com/201430/71101348-8771c000-2184-11ea-8319-a1cd09ee8f63.png)

It seems to be a duplicate of #342, #296 and #293, but I have the newer versions of everything, and still fails.

PHP Version:

![image](https://user-images.githubusercontent.com/201430/71101429-b2f4aa80-2184-11ea-8486-9952b6ef21b4.png)

**Comment by citosid** [comment]
FWIW, here is the trace:

```text
[Error - 10:50:31 AM] Request textDocument/definition failed.
  Message: RuntimeException: A type is missing in an array expression in /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/type-resolver/src/TypeResolver.php:257
Stack trace:
#0 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/type-resolver/src/TypeResolver.php(195): phpDocumentor\Reflection\TypeResolver->parseTypes(Object(ArrayIterator), Object(phpDocumentor\Reflection\Types\Context), 2)
#1 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/type-resolver/src/TypeResolver.php(146): phpDocumentor\Reflection\TypeResolver->parseTypes(Object(ArrayIterator), Object(phpDocumentor\Reflection\Types\Context), 0)
#2 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Param.php(75): phpDocumentor\Reflection\TypeResolver->resolve('array()', Object(phpDocumentor\Reflection\Types\Context))
#3 [internal function]: phpDocumentor\Reflection\DocBlock\Tags\Param::create('array() $header...', Object(phpDocumentor\Reflection\TypeResolver), Object(phpDocumentor\Reflection\DocBlock\DescriptionFactory), Object(phpDocumentor\Reflection\Types\Context))
#4 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(201): call_user_func_array(Array, Array)
#5 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('array() $header...', 'param', Object(phpDocumentor\Reflection\Types\Context))
#6 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(231): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@param array() ...', Object(phpDocumentor\Reflection\Types\Context))
#7 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(96): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('@param $url\n@pa...', Object(phpDocumentor\Reflection\Types\Context))
#8 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/DefinitionResolver.php(166): phpDocumentor\Reflection\DocBlockFactory->create('/**\n     * @par...', Object(phpDocumentor\Reflection\Types\Context))
#9 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/DefinitionResolver.php(1127): LanguageServer\DefinitionResolver->getDocBlock(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#10 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/DefinitionResolver.php(240): LanguageServer\DefinitionResolver->getTypeFromNode(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#11 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(157): LanguageServer\DefinitionResolver->createDefinitionFromNode(Object(Microsoft\PhpParser\Node\MethodDeclaration), 'Jumbojett\\OpenI...')
#12 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(124): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#13 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#14 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\ClassMembersNode))
#15 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#16 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/TreeAnalyzer.php(58): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\SourceFileNode))
#17 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\n\n/**\n *\n ...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///Users/a...')
#18 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\n\n/**\n *\n ...')
#19 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///Users/a...', '<?php\n\n/**\n *\n ...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#20 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///Users/a...', '<?php\n\n/**\n *\n ...')
#21 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#22 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\n\n/**\n *\n ...')
#23 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\n\n/**\n *\n ...')
#24 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#25 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#26 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#27 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#28 /Users/acruz/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/felixfbecker/language-server/bin/php-language-server.php(55): Sabre\Event\Loop\run()
#29 {main}
  Code: -32603 
```

**Comment by LadislauStrifler** [comment]
Have the same issue here when intellisense is trying to parse a [smarty plugin file](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatebase.php).

Almost the same stack trace and error code applies.

````
[Error - 01:46:36] Request textDocument/documentSymbol failed. Message: RuntimeException: A type is missing in an array expression in \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\type-resolver\src\TypeResolver.php:257
Stack trace:
#0 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\type-resolver\src\TypeResolver.php(195): phpDocumentor\Reflection\TypeResolver->parseTypes(Object(ArrayIterator), Object(phpDocumentor\Reflection\Types\Context), 2)
#1 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\type-resolver\src\TypeResolver.php(146): phpDocumentor\Reflection\TypeResolver->parseTypes(Object(ArrayIterator), Object(phpDocumentor\Reflection\Types\Context), 0)
#2 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\Tags\Var_.php(68): phpDocumentor\Reflection\TypeResolver->resolve('array()', Object(phpDocumentor\Reflection\Types\Context))
#3 [internal function]: phpDocumentor\Reflection\DocBlock\Tags\Var_::create('array()', Object(phpDocumentor\Reflection\TypeResolver), Object(phpDocumentor\Reflection\DocBlock\DescriptionFactory), Object(phpDocumentor\Reflection\Types\Context))
#4 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(201): call_user_func_array(Array, Array)
#5 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('array()', 'var', Object(phpDocumentor\Reflection\Types\Context))
#6 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlockFactory.php(231): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@var array()', Object(phpDocumentor\Reflection\Types\Context))
#7 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlockFactory.php(96): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('@var array()', Object(phpDocumentor\Reflection\Types\Context))
#8 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\DefinitionResolver.php(166): phpDocumentor\Reflection\DocBlockFactory->create('/**\r\n     * uni...', Object(phpDocumentor\Reflection\Types\Context))
#9 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\DefinitionResolver.php(1195): LanguageServer\DefinitionResolver->getDocBlock(Object(Microsoft\PhpParser\Node\PropertyDeclaration))
#10 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\DefinitionResolver.php(240): LanguageServer\DefinitionResolver->getTypeFromNode(Object(Microsoft\PhpParser\Node\Expression\Variable))
#11 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(157): LanguageServer\DefinitionResolver->createDefinitionFromNode(Object(Microsoft\PhpParser\Node\Expression\Variable), 'Smarty_Internal...')
#12 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(124): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\Variable))
#13 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\Variable))
#14 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#15 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\DelimitedList\ExpressionList))
#16 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\PropertyDeclaration))
#17 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\ClassMembersNode))
#18 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#19 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(58): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\SourceFileNode))
#20 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\r\n/**\r\n * ...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///d:/www/...')
#21 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\r\n/**\r\n * ...')
#22 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///d:/www/...', '<?php\r\n/**\r\n * ...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#23 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///d:/www/...', '<?php\r\n/**\r\n * ...')
#24 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#25 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\coroutine.php(70): Generator->send('<?php\r\n/**\r\n * ...')
#26 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}('<?php\r\n/**\r\n * ...')
#27 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#28 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#29 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#30 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#31 \%UserPath%\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php(55): Sabre\Event\Loop\run()
#32 {main}
  Code: -32603 
````
