### ISSUE TITLE
Call to undefined function AdvancedJsonRpc\json_decode()

### ISSUE THREAD

**Issue by rdlmda** [felixfbecker/php-language-server#775]
```
PHP Language Server: CRITICAL  Error: Call to undefined function AdvancedJsonRpc\json_decode() in /home/user/.vscode-oss/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/advanced-json-rpc/lib/Message.php:26
Stack trace:
#0 /home/user/.vscode-oss/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/src/ProtocolStreamReader.php(55): AdvancedJsonRpc\Message::parse('{"jsonrpc":"2.0...')
#1 /home/user/.vscode-oss/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#2 /home/user/.vscode-oss/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#3 /home/user/.vscode-oss/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#4 /home/user/.vscode-oss/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#5 /home/user/.vscode-oss/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/bin/php-language-server.php(55): Sabre\Event\Loop\run()
#6 {main}
```

**Comment by rdlmda** [comment]
I had `php-cli` installed on Fedora (but not `php`), installing `php-json` solved the issue.
