### ISSUE TITLE
UnexpectedValueException: RecursiveDirectoryIterator

### ISSUE THREAD

**Issue by williamdes** [felixfbecker/php-language-server#785]
```
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/mnt/Dev/!OSS/work1/work): failed to open dir: Permission denied in /home/williamdes/.vscode-insiders/extensions/felixfbecker.php-intellisense-2.3.14/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php:43
Stack trace: #0 /home/williamdes/.vscode-insiders/extensions/felixfbecker.php-intellisense-2.3.14/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct()
#1 /home/williamdes/.vscode-insiders/extensions/felixfbecker.php-intellisense-2.3.14/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct()
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 /home/williamdes/.vscode-insiders/extensions/felixfbecker.php-intellisense-2.3.14/vendor/webmozart/glob/src/Iterator/RegexFilterIterator.php(99): FilterIterator->rewind() #4 [internal funct...
```
This is an error I have each time I open my workspace, could you add a safe guard so it does not happen ?

**Comment by zorn-v** [comment]
Same here. And nothing worked (goto class by click etc) after that

**Comment by FaisalBudiono** [comment]
+1, I also facing the same error whenever I install the PHP intelesense

**Comment by zorn-v** [comment]
Seems it is long story
https://github.com/felixfbecker/php-language-server/issues/462

**Comment by williamdes** [comment]
https://github.com/felixfbecker/php-language-server/issues/462#issuecomment-891207364
