### ISSUE TITLE
PHP8 Not compatible ?

### ISSUE THREAD

**Issue by theCrazylegs** [felixfbecker/php-language-server#809]
Everything is in the title

`ErrorException: Method ReflectionParameter::getClass() is deprecated in C:\Users\xxxxx\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php:241 Stack trace: #0 C:\Users\xxxxx\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', 'C:\\Users\\xxxxx\\...', 241) #1 C:\Users\xxxxx\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(198): phpDocumentor\Reflection\DocBlock\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array) #2 C:\Users\xxxxx\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('ClientCapabilit...', 'param', Object(phpDocumentor\Refl...`

**Comment by GwynethLlewelyn** [comment]
I'd guess that's because this project hasn't been updated since **2018**, but PHP 8.0 was launched only on November 26, **2020**. Therefore, it ought not to be able to parse any recent PHP version...

**Comment by rk0cc** [comment]
> I'd guess that's because this project hasn't been updated since **2018**, but PHP 8.0 was launched only on November 26, **2020**. Therefore, it ought not to be able to parse any recent PHP version...

So, does any forked repos that supported already?

**Comment by GwynethLlewelyn** [comment]
> So, does any forked repos that supported already?

Excellent question, I wish I knew I had an answer. But I guess that everybody is moving to [Intelephense](https://intelephense.com/) anyway. It's _freemium_ software, but a lifetime license costs only €12, so there is probably not much of an incentive to keep developing something from scratch _and_ keep it up-to-date...

**Comment by Ben-CA** [comment]
It's unfortunate this software hasn't been updated to support PHP 8.0

**Comment by GwynethLlewelyn** [comment]
Alas, you're right, and the probability of it ever getting updated again is tiny.

**Comment by rk0cc** [comment]
I just found [zobo's forked repos](https://github.com/zobo/php-language-server) maybe worked up to PHP 8.1 (in GitHub action, officially said 'work in progress') when this comment posted and changed the minimum PHP version to 7.4.

It's also provides it's own [Code extension](https://github.com/zobo/vscode-php-intellisense) ~~but required install from .vsix file manually~~ and [published](https://marketplace.visualstudio.com/items?itemName=zobo.php-intellisense) already.
